# Data Preparation

This code block creates a `DataFrame` object that will be used by other code blocks in this page. Please make sure that you run it before running other code blocks in this page.

In [1]:
#source of data: https://www.pewresearch.org/social-trends/2014/04/10/next-america/#the-generational-divide
import pandas as pd
population_data = {'Year':[1960, 1970, 1980, 1990, 2000, 2010, 2020, 2030, 2040, 2050, 2060],
                  'White':[.85, .83, .80, .76, .69, .64, .60, .55, .51, .47, .43],
                  'Black': [.10, .11, .12, .12, .12, .12, .13, .13, .13, .13, .13],
                  'Hispanic': [.04, .05, .06, .09, .13, .16, .19, .22, .25, .28, .31],
                  'Asian': [.01, .01, .02, .03, .04, .05, .06, .06, .07, .08, .08],
                  'Others': [.00, .00, .01, .01, .02, .03, .03, .04, .04, .05, .06]}
population_df = pd.DataFrame(population_data)
population_df

#make sure that you run this code block before running the code blocks below

    Year  White  Black  Hispanic  Asian  Others
0   1960   0.85   0.10      0.04   0.01    0.00
1   1970   0.83   0.11      0.05   0.01    0.00
2   1980   0.80   0.12      0.06   0.02    0.01
3   1990   0.76   0.12      0.09   0.03    0.01
4   2000   0.69   0.12      0.13   0.04    0.02
5   2010   0.64   0.12      0.16   0.05    0.03
6   2020   0.60   0.13      0.19   0.06    0.03
7   2030   0.55   0.13      0.22   0.06    0.04
8   2040   0.51   0.13      0.25   0.07    0.04
9   2050   0.47   0.13      0.28   0.08    0.05
10  2060   0.43   0.13      0.31   0.08    0.06

# Select column(s)

To access one column of a DataFrame object, we simply use the name of the DataFrame object followed by a pair of square brackets. Inside the square brackets, we add the name of the column. As a reminder, text is case sensitive in Python.

In [ ]:
population_df['White']

0     0.85
1     0.83
2     0.80
3     0.76
4     0.69
5     0.64
6     0.60
7     0.55
8     0.51
9     0.47
10    0.43
Name: White, dtype: float64

Each column of a DataFrame object is a Series object. DataFrame and Series share many attributes and functions. For example, the following code block shows how to access the info function for the 'White' column of population_df.

In [ ]:
population_df['White'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 11 entries, 0 to 10
Series name: White
Non-Null Count  Dtype
--------------  -----
11 non-null     float64
dtypes: float64(1)
memory usage: 220.0 bytes

As shown by the result of the above code block, population_df['White'] is a Series object whose name is White. It has 11 non-null values and each value is a floating point value.

The following code block shows how we can save a column of a DataFrame object into a variable and then work with the variable.

In [ ]:
# This is to set the display format for floating point values
pd.options.display.float_format = "{:.2f}".format

# This is to save a column of a DataFrame into a variable
white = population_df['White']

# Then we can reference the column using the variable
print('the result of the shape attribute', white.shape)
print('the result of the describe function: is shown below')
white.describe()

the result of the shape attribute (11,)
the result of the describe function

count   11.00
mean     0.65
std      0.15
min      0.43
25%      0.53
50%      0.64
75%      0.78
max      0.85
Name: White, dtype: float64

We can also select a list of columns from a DataFrame object. To do that, we can do so in two steps.

In [ ]:
list = ['Year', 'White']
population_df[list]

    Year  White
0   1960   0.85
1   1970   0.83
2   1980   0.80
3   1990   0.76
4   2000   0.69
5   2010   0.64
6   2020   0.60
7   2030   0.55
8   2040   0.51
9   2050   0.47
10  2060   0.43

We can also put the list directly inside population_df[] as shown below. Note that two pairs of [ ] are used.

In [ ]:
population_df[['Year', 'White']]

    Year  White
0   1960   0.85
1   1970   0.83
2   1980   0.80
3   1990   0.76
4   2000   0.69
5   2010   0.64
6   2020   0.60
7   2030   0.55
8   2040   0.51
9   2050   0.47
10  2060   0.43

When multiple columns are selected, the result is another DataFrame object as shown by the following code block.

In [ ]:
white_df = population_df[['Year', 'White']]
print('Shape of the new df', white_df.shape)
print('Columns of the new df', white_df.columns)
print('The result of the info function is shown below:')
white_df.info()

Shape of the new df (11, 2)
Columns of the new df Index(['Year', 'White'], dtype='object')
The result of the info function is shown below:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    11 non-null     int64
 1   White   11 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 308.0 bytes

## Practice

In [ ]:
# Save data for another race of your choice into a respective variable
asian = population_df['Asian']

In [ ]:
# Call the info function for the above variable
asian.info()

<class 'pandas.core.series.Series'>
RangeIndex: 11 entries, 0 to 10
Series name: Asian
Non-Null Count  Dtype
--------------  -----
11 non-null     float64
dtypes: float64(1)
memory usage: 220.0 bytes

In [ ]:
# Call the shape attribute for the above variable

In [ ]:
# Call the describe function for the above variable

In [ ]:
# Save data for the 'Year' and two race columns into a respective variable
# Show the shape and columns attributes for the new variable

# Filtering by One comparison

In [ ]:
population_df

    Year  White  Black  Hispanic  Asian  Others
0   1960   0.85   0.10      0.04   0.01    0.00
1   1970   0.83   0.11      0.05   0.01    0.00
2   1980   0.80   0.12      0.06   0.02    0.01
3   1990   0.76   0.12      0.09   0.03    0.01
4   2000   0.69   0.12      0.13   0.04    0.02
5   2010   0.64   0.12      0.16   0.05    0.03
6   2020   0.60   0.13      0.19   0.06    0.03
7   2030   0.55   0.13      0.22   0.06    0.04
8   2040   0.51   0.13      0.25   0.07    0.04
9   2050   0.47   0.13      0.28   0.08    0.05
10  2060   0.43   0.13      0.31   0.08    0.06

The following code block creates a new DataFrame that contain rows whose White column have values that are under 0.5.

In [ ]:
white = population_df['White']
white_under_50_percent = population_df[white < 0.5]
white_under_50_percent

We can also specify the filtering condition beforehand as shown in the following code block.

In [ ]:
filtering_condition = population_df['White'] < 0.5
white_under_50_percent = population_df[filtering_condition]
white_under_50_percent

    Year  White  Black  Hispanic  Asian  Others
9   2050   0.47   0.13      0.28   0.08    0.05
10  2060   0.43   0.13      0.31   0.08    0.06

We can also combine the intermediate steps and achieve the same goal via the following.

In [ ]:
white_under_50_percent = population_df[population_df['White'] < 0.5]
white_under_50_percent

    Year  White  Black  Hispanic  Asian  Others
9   2050   0.47   0.13      0.28   0.08    0.05
10  2060   0.43   0.13      0.31   0.08    0.06

It is important to know that the filtering creates a new DataFrame without changing the original. Run the following code block to see the original DataFrame.

In [ ]:
population_df

    Year  White  Black  Hispanic  Asian  Others
0   1960   0.85   0.10      0.04   0.01    0.00
1   1970   0.83   0.11      0.05   0.01    0.00
2   1980   0.80   0.12      0.06   0.02    0.01
3   1990   0.76   0.12      0.09   0.03    0.01
4   2000   0.69   0.12      0.13   0.04    0.02
5   2010   0.64   0.12      0.16   0.05    0.03
6   2020   0.60   0.13      0.19   0.06    0.03
7   2030   0.55   0.13      0.22   0.06    0.04
8   2040   0.51   0.13      0.25   0.07    0.04
9   2050   0.47   0.13      0.28   0.08    0.05
10  2060   0.43   0.13      0.31   0.08    0.06

The above filtering compares one column against a target value. We can also compare two columns as illustrated in the following code block.

In [ ]:
# Create a new DataFrame with rows whose Black percentage is higher than Hispanic percentage
black = population_df['Black']
hispanic = population_df['Hispanic']
filtering_condition = black > hispanic
# The above three lines can be rewritten into
# filtering_condition = population_df['Black'] > population_df['Hispanic']

more_black_than_hispanic = population_df[filtering_condition]
more_black_than_hispanic

   Year  White  Black  Hispanic  Asian  Others
0  1960   0.85   0.10      0.04   0.01    0.00
1  1970   0.83   0.11      0.05   0.01    0.00
2  1980   0.80   0.12      0.06   0.02    0.01
3  1990   0.76   0.12      0.09   0.03    0.01

## Practice

In [ ]:
# Create a new DataFrame of rows whose white column value is above 60%.
# Save the new DataFrame in a descriptive name and show its values.

In [ ]:
# Create a new DataFrame using a race of your choice and a comparison of your choice.
# Save the new DataFrame in a descriptive name and show its values.

In [ ]:
# Create a new DataFrame with rows whose Black percentage is higher than Hispanic percentage
# Save the new DataFrame in a descriptive name and show its values.

# The & and | logical Operators

Similar to list comprehension, we can use the logical operators. However, pandas uses **& for and, | for or**. Since the &, and | operators have lower precedence than the comparison operators, it is important to put a pair of parentheses around the comparisons.

The following code block shows an example of filtering based on white values between 30% and 60%, i.e. 0.3 and 0.6.

In [ ]:
# Rows where the percentage for white is between 30 and 60 percent.
white = population_df['White']
filtering_condition = (white >= 0.3) & (white <= 0.6)
between_30_60_percent = population_df[filtering_condition]
between_30_60_percent

    Year  White  Black  Hispanic  Asian  Others
6   2020   0.60   0.13      0.19   0.06    0.03
7   2030   0.55   0.13      0.22   0.06    0.04
8   2040   0.51   0.13      0.25   0.07    0.04
9   2050   0.47   0.13      0.28   0.08    0.05
10  2060   0.43   0.13      0.31   0.08    0.06

The following code block shows an example filtering values outside of the 30 - 60 range. That is, we are looking for white percentage either less than 30% or greater than 60%.

In [ ]:
# Rows where the percentage for white is either under 30 or above 60 percent.
filtering_condition = (population_df['White'] < 0.3) | (population_df['White'] > 0.6)
beyond_30_60_percent = population_df[filtering_condition]
beyond_30_60_percent

   Year  White  Black  Hispanic  Asian  Others
0  1960   0.85   0.10      0.04   0.01    0.00
1  1970   0.83   0.11      0.05   0.01    0.00
2  1980   0.80   0.12      0.06   0.02    0.01
3  1990   0.76   0.12      0.09   0.03    0.01
4  2000   0.69   0.12      0.13   0.04    0.02
5  2010   0.64   0.12      0.16   0.05    0.03

We can use the | operator to help us choose rows for selected years.

In [ ]:
filtering_condition = (population_df['Year'] == 1990) | (population_df['Year'] == 2010) | (population_df['Year'] == 2030)
years_1990_2010_2030 = population_df[filtering_condition]
years_1990_2010_2030

   Year  White  Black  Hispanic  Asian  Others
3  1990   0.76   0.12      0.09   0.03    0.01
5  2010   0.64   0.12      0.16   0.05    0.03
7  2030   0.55   0.13      0.22   0.06    0.04

We can also use the & operator to help us exclude rows from selected years.

In [ ]:
filtering_condition = (population_df['Year'] != 1990) & (population_df['Year'] != 2010) & (population_df['Year'] != 2030)
years_not_1990_2010_2030 = population_df[filtering_condition]
years_not_1990_2010_2030

    Year  White  Black  Hispanic  Asian  Others
0   1960   0.85   0.10      0.04   0.01    0.00
1   1970   0.83   0.11      0.05   0.01    0.00
2   1980   0.80   0.12      0.06   0.02    0.01
4   2000   0.69   0.12      0.13   0.04    0.02
6   2020   0.60   0.13      0.19   0.06    0.03
7   2030   0.55   0.13      0.22   0.06    0.04
8   2040   0.51   0.13      0.25   0.07    0.04
9   2050   0.47   0.13      0.28   0.08    0.05
10  2060   0.43   0.13      0.31   0.08    0.06

The comparisons connected by a logical operator can compare different columns.

In [ ]:
# Rows with high Black and Hispanic percentage
filtering_condition = (population_df['Black'] > 0.12) & (population_df['Hispanic'] > 0.12)
high_black_hispanic = population_df[filtering_condition]
high_black_hispanic

    Year  White  Black  Hispanic  Asian  Others
6   2020   0.60   0.13      0.19   0.06    0.03
7   2030   0.55   0.13      0.22   0.06    0.04
8   2040   0.51   0.13      0.25   0.07    0.04
9   2050   0.47   0.13      0.28   0.08    0.05
10  2060   0.43   0.13      0.31   0.08    0.06

## Practice

In [ ]:
# Create a new DataFrame to hold only rows of population_df whose Hispanic percentage
# is between a range values of your choice
# Save the new DataFrame in a descriptive variable name and show its values

In [ ]:
# Create a new DataFrame to hold only rows of population_df whose Hispanic percentage
# is outside a range values of your choice
# Save the new DataFrame in a descriptive variable name and show its values

In [ ]:
# Create a new DataFrame to hold only rows of population_df whose Hispanic percentage
# is one of two values of your choice
# Save the new DataFrame in a descriptive variable name and show its values

In [ ]:
# Create a new DataFrame to hold only rows of population_df whose Hispanic percentage
# is neither two values of your choice
# Save the new DataFrame in a descriptive variable name and show its values

In [ ]:
# Use the & operator to create a new DataFrame to hold only rows of population_df
# whose White percentage is above than 50% and Hispanice percentage is lower than 25%
# Save the new DataFrame in a descriptive variable name and show its values

# The isin function and the ~ operator

In addition, pandas supports the **isin** function for that we can use to check if a given value belongs to a list of values.

The following code block shows an example of filtering based on the 'Year' column.

In [2]:
selected_years = [1960, 1990, 2020, 2060]
condition = population_df['Year'].isin(selected_years)
from_selected_years = population_df[condition]
from_selected_years

    Year  White  Black  Hispanic  Asian  Others
0   1960   0.85   0.10      0.04   0.01    0.00
3   1990   0.76   0.12      0.09   0.03    0.01
6   2020   0.60   0.13      0.19   0.06    0.03
10  2060   0.43   0.13      0.31   0.08    0.06

The ~ operator is a logical operator that negate an original Boolean value. It can be used along with a condition to choose rows that do not meet the condition.

In [ ]:
filtering_condition = population_df['Year'].isin([1960, 1980, 2010, 2030, 2050])
outside_selected_years = population_df[~filtering_condition]
outside_selected_years

    Year  White  Black  Hispanic  Asian  Others
1   1970   0.83   0.11      0.05   0.01    0.00
3   1990   0.76   0.12      0.09   0.03    0.01
4   2000   0.69   0.12      0.13   0.04    0.02
6   2020   0.60   0.13      0.19   0.06    0.03
8   2040   0.51   0.13      0.25   0.07    0.04
10  2060   0.43   0.13      0.31   0.08    0.06

### Practice

In [ ]:
# Use the isin function to create a new DataFrame using rows from four years of your choice.
# Save the new DataFrame in a descriptive variable name and show its values.

In [ ]:
# Use the combination of ~ and the isin function to create a new DataFrame that have years
# other than five years of your choice
# Save the new DataFrame in a descriptive variable name and show its values