# Data Preparation

The following data are extracted from the [HDPulse Data Portal](https://hdpulse.nimhd.nih.gov/data-portal/home). Run the code block before working on the rest of the code blocks on this page.

In [1]:
import pandas as pd

# Set up the data using a dictionary structure
data = {
    'State': ['Arizona', 'California', 'Colorado', 'Idaho', 'Montana', 'Nevada', 'New Mexico', 'Oregon', 'Utah', 'Washington', 'Wyoming'],
    'Incarceration': [6.6, 4.2, 6.4, 7.7, 8.6, 4.5, 7.4, 5.0, 4.1, 6.1, 10.3],
    'Poverty': [8.9, 8.4, 5.9, 7.0, 7.1, 9.0, 13.7, 7.3, 5.7, 6.4, 7.1]
}

# Create and save a DataFrame object using the above data
df = pd.DataFrame(data)

## Practice

Complete the following tasks to do an initial inspection of the dataset. Review examples from previous classes.

In [ ]:
# Use an appropriate attribute to find out the numbers of rows and columns of the DataFrame object

In [ ]:
# Call an appropriate function to learn more about the structure and size of the DataFrame object

In [ ]:
# Call an appropriate function to show the top three rows of the DataFrame object

In [ ]:
# Call an apprpriate function to show descriptive statistics of the DataFrame object

# Ranking

The `describe` function show the smallest and highest values of incarceration and poverty. However, it does not tell us which states have these values. **Ranking** assigns an order position to each row based on the values of a numeric column. This can be achieved using the `rank` function as shown in the following code block.

*  The `rank` function does not change any value in `df['Incarceration']`.
*  It does not rearrange the rows of the DataFrame object.
*  It simply creates a new `Series` that can be assigned to a new column of the DataFrame object.
*  `ascending=False` indicates that the highest value will get first rank. If we want the lowest value to get the first rank, we should set `ascending=True`.
*  `method='dense'` indicates that there will be no gaps in ranks and ties share a rank. If we want tied values to get the best (lowest) rank and the next rank skips, we will need to use `method='min'`

In [ ]:
df['Incarceration_rank'] = df['Incarceration'].rank(ascending=False, method='dense')
df

         State  Incarceration  Poverty  Incarceration_rank
0      Arizona            6.6      8.9                 5.0
1   California            4.2      8.4                10.0
2     Colorado            6.4      5.9                 6.0
3        Idaho            7.7      7.0                 3.0
4      Montana            8.6      7.1                 2.0
5       Nevada            4.5      9.0                 9.0
6   New Mexico            7.4     13.7                 4.0
7       Oregon            5.0      7.3                 8.0
8         Utah            4.1      5.7                11.0
9   Washington            6.1      6.4                 7.0
10     Wyoming           10.3      7.1                 1.0

If we want the lowest value to receive 1 as its rank, we need to set `ascending=True` as shown in the following code block.

In [5]:
df['Incarceration_rank'] = df['Incarceration'].rank(ascending=True, method='dense')
df

         State  Incarceration  Poverty  Incarceration_rank
0      Arizona            6.6      8.9                 7.0
1   California            4.2      8.4                 2.0
2     Colorado            6.4      5.9                 6.0
3        Idaho            7.7      7.0                 9.0
4      Montana            8.6      7.1                10.0
5       Nevada            4.5      9.0                 3.0
6   New Mexico            7.4     13.7                 8.0
7       Oregon            5.0      7.3                 4.0
8         Utah            4.1      5.7                 1.0
9   Washington            6.1      6.4                 5.0
10     Wyoming           10.3      7.1                11.0

In [6]:
condition = df['Incarceration_rank'] < 5
df[condition]

        State  Incarceration  Poverty  Incarceration_rank
1  California            4.2      8.4                 2.0
5      Nevada            4.5      9.0                 3.0
7      Oregon            5.0      7.3                 4.0
8        Utah            4.1      5.7                 1.0

## Practice

In [ ]:
# Add and show rankings for poverty using the highest poverty as 1.
# Since there are ties for poverty, use method='dense' to break ties

In [ ]:
# Update and show rankings for poverty using the lowest poverty as 1
# Use method='min' to break ties and see how it works differently than method='dense'

# Sorting

Adding the rank columns do not change the order of the original rows. Sorting, on the other hand, creates a new DataFrame object where the rows are rearranged rows based on column values.

In [10]:
df.sort_values(by='Incarceration', ascending=True)

         State  Incarceration  Poverty  Incarceration_rank
8         Utah            4.1      5.7                 1.0
1   California            4.2      8.4                 2.0
5       Nevada            4.5      9.0                 3.0
7       Oregon            5.0      7.3                 4.0
9   Washington            6.1      6.4                 5.0
2     Colorado            6.4      5.9                 6.0
0      Arizona            6.6      8.9                 7.0
6   New Mexico            7.4     13.7                 8.0
3        Idaho            7.7      7.0                 9.0
4      Montana            8.6      7.1                10.0
10     Wyoming           10.3      7.1                11.0

By default, the sort_values function creates a new DataFrame object without changing the original DataFrame object. Run the following code block and you'll see that the original DataFrame object remained unsorted.

In [11]:
df

         State  Incarceration  Poverty  Incarceration_rank
0      Arizona            6.6      8.9                 7.0
1   California            4.2      8.4                 2.0
2     Colorado            6.4      5.9                 6.0
3        Idaho            7.7      7.0                 9.0
4      Montana            8.6      7.1                10.0
5       Nevada            4.5      9.0                 3.0
6   New Mexico            7.4     13.7                 8.0
7       Oregon            5.0      7.3                 4.0
8         Utah            4.1      5.7                 1.0
9   Washington            6.1      6.4                 5.0
10     Wyoming           10.3      7.1                11.0

There are two ways to rearrange the rows of the orginal DataFrame object.

The first, and preferred way, is to simply assigned the newly created DataFrame object by the sort_values function back to the original DataFrame object.

In [ ]:
df = df.sort_values(by='Incarceration', ascending=False)
df

         State  Incarceration  Poverty  Incarceration_rank
10     Wyoming           10.3      7.1                 1.0
4      Montana            8.6      7.1                 2.0
3        Idaho            7.7      7.0                 3.0
6   New Mexico            7.4     13.7                 4.0
0      Arizona            6.6      8.9                 5.0
2     Colorado            6.4      5.9                 6.0
9   Washington            6.1      6.4                 7.0
7       Oregon            5.0      7.3                 8.0
5       Nevada            4.5      9.0                 9.0
1   California            4.2      8.4                10.0
8         Utah            4.1      5.7                11.0

Another way, discouraged by the pandas community, is to use inplace=True

In [ ]:
df.sort_values(by='Incarceration', ascending=True, inplace=True)
df

         State  Incarceration  Poverty  Incarceration_rank
8         Utah            4.1      5.7                11.0
1   California            4.2      8.4                10.0
5       Nevada            4.5      9.0                 9.0
7       Oregon            5.0      7.3                 8.0
9   Washington            6.1      6.4                 7.0
2     Colorado            6.4      5.9                 6.0
0      Arizona            6.6      8.9                 5.0
6   New Mexico            7.4     13.7                 4.0
3        Idaho            7.7      7.0                 3.0
4      Montana            8.6      7.1                 2.0
10     Wyoming           10.3      7.1                 1.0

## Practice

In [ ]:
# Sort the dataset by state and update the original DataFrame

In [ ]:
# Sort the dataset by poverty and update the original DataFrame

# Counting

Last time, we learned about setting up filtering conditions to extract specific rows. When applying a condition to a column, pandas will evaluate each value in the column and returns True if the value meets the condition, False if the value does not meet the condition.

In [12]:
df

         State  Incarceration  Poverty  Incarceration_rank
0      Arizona            6.6      8.9                 7.0
1   California            4.2      8.4                 2.0
2     Colorado            6.4      5.9                 6.0
3        Idaho            7.7      7.0                 9.0
4      Montana            8.6      7.1                10.0
5       Nevada            4.5      9.0                 3.0
6   New Mexico            7.4     13.7                 8.0
7       Oregon            5.0      7.3                 4.0
8         Utah            4.1      5.7                 1.0
9   Washington            6.1      6.4                 5.0
10     Wyoming           10.3      7.1                11.0

In [13]:
filtering_condition = (df['Incarceration'] > 5.5) & (df['Incarceration'] <= 7.1)
filtering_condition

0      True
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
Name: Incarceration, dtype: bool

As shown by the above result, there are three rows that return True for the condition. In Python, and many programming languages, True is consider 1 and False is consider 0. Therefore, we can use the sum function to help us add up the values of 1 as a way to count the number of values in a column that meet the condition.

In [ ]:
filtering_condition.sum()

np.int64(3)

The np in the above result is a common alias for NumPy, another popular third party Python library. The result np.int64(3) indicates that there are 3 rows in the dataset that meets the filtering condition.

The following code block shows more examples of using filtering conditions to help count related rows.

In [ ]:
under_condition = df['Incarceration'] <= 5.5
above_condition = df['Incarceration'] > 7.1
between_condition = (df['Incarceration'] > 5.5) & (df['Incarceration'] <= 7.1)
outside_condition = (df['Incarceration'] <= 5.5) | (df['Incarceration'] > 7.1)
under_count = under_condition.sum()
above_count = above_condition.sum()
between_count = between_condition.sum()
outside_count = outside_condition.sum()
print(f'There are {under_count} states with incarceration under 5.5')
print(f'There are {above_count} states with incarceration above 7.1')
print(f'There are {between_count} states with incarceration between 5.5 and 7.1')
print(f'There are {outside_count} states with incarceration outside of the range of 5.5 and 7.1')

There are 4 states with incarceration under 5.5
There are 4 states with incarceration above 7.1
There are 3 states with incarceration between 5.5 and 7.1
There are 8 states with incarceration outside of the range of 5.5 and 7.1

## Practice

In [ ]:
# Count and show the number of states whose poverty values are under 6.7

In [ ]:
# Count and show the number of states whose poverty values are above 8.8

In [ ]:
# Count and show the number of states whose poverty values are within the range of 6.7 and 8.8

In [ ]:
# Count and show the number of states whose poverty values are outside of the range of 6.7 and 8.8

# Classify numeric data by ranges

The maps on HDPulse use different shades of blue to help people visualize the incarceration and poverty levels. We are not quite ready to learn how to generate such maps. However, it is actually quite easy to classify numeric values into categories based on ranges.

The `cut` function takes a few parameters:

*  The first parameter is the numeric column for which we wan to classify.
*  The `bins` parameter specifies the ranges that will be used to break down the numeric values. By default, the ranges are lower/left exclusive and upper/right inclusive.  
*  The `labels` parameter specifies the labels for respective ranges.

The following two code blocks show different ways of classifying incarceration rates.

In [ ]:
# This will mark values > 1.6 to 4.1 as low, >4.1 to 5.5 as medium low,
# > 5.5 to 7.1 as medium, > 7.1 to 8.6 as medium high, and >8.6 to 12.6 as high
# Right/upper inclusive means 4.1 belongs to the first bin
# Left/lower exclusive means 4.1 does not belong to the second bin
incarceration_bins = [1.6, 4.1, 5.5, 7.1, 8.6, 12.6]
incarceration_labels = ['low', 'medium low', 'medium', 'medium high', 'high']
df['Incarceration_Level'] = pd.cut(df['Incarceration'],
                                   bins = incarceration_bins,
                                   labels = incarceration_labels)
df

         State  Incarceration  Poverty  Incarceration_rank Incarceration_Level
8         Utah            4.1      5.7                11.0                 low
1   California            4.2      8.4                10.0          medium low
5       Nevada            4.5      9.0                 9.0          medium low
7       Oregon            5.0      7.3                 8.0          medium low
9   Washington            6.1      6.4                 7.0              medium
2     Colorado            6.4      5.9                 6.0              medium
0      Arizona            6.6      8.9                 5.0              medium
6   New Mexico            7.4     13.7                 4.0         medium high
3        Idaho            7.7      7.0                 3.0         medium high
4      Montana            8.6      7.1                 2.0         medium high
10     Wyoming           10.3      7.1                 1.0                high

We can make the bins left/lower inclusive and right/upper exclusive by setting the right parameter to False as shown in the following code block.

*  Left/lower inclusive means 1.6 belong to the first bin and 5.6 belongs to the second bin.
*  Right/upper exclusive means 5.6 does not belong to the first bin.

In [ ]:
# This will mark values 1.6 to <5.6 as low, 5.6 to <8.7 as medium, 8.7 to <12.6 as high
incarceration_bins = [1.6, 5.5, 8.6, 12.6]
incarceration_labels = ['low', 'medium', 'high']
df['Incarceration_Level'] = pd.cut(df['Incarceration'],
                                   bins = incarceration_bins,
                                   labels = incarceration_labels,
                                   right=False)
df

         State  Incarceration  Poverty  Incarceration_rank Incarceration_Level
8         Utah            4.1      5.7                11.0                 low
1   California            4.2      8.4                10.0                 low
5       Nevada            4.5      9.0                 9.0                 low
7       Oregon            5.0      7.3                 8.0                 low
9   Washington            6.1      6.4                 7.0              medium
2     Colorado            6.4      5.9                 6.0              medium
0      Arizona            6.6      8.9                 5.0              medium
6   New Mexico            7.4     13.7                 4.0              medium
3        Idaho            7.7      7.0                 3.0              medium
4      Montana            8.6      7.1                 2.0              medium
10     Wyoming           10.3      7.1                 1.0                high

## Practice

In [ ]:
# Set up appropriate bins and labels to label the poverty levels into low, medium,
# and high according to values of your choice using right inclusive

In [ ]:
# Set up appropriate bins and labels to label the poverty levels of your choice
# according to values of your choice using right exclusive